### ISSUE TITLE
u16 register addr no longer builds

### ISSUE THREAD

**Issue by IsaacDynamo** [diondokter/device-driver#96]
Current master fails when `RegisterAddressType` in `create_device!()` and `DeviceInterface::AddressType` in the `basic-register` test are changed from `u8` to `u16`.

The error is as follows:

```Rust
error[E0308]: mismatched types
  --> device-driver/tests/basic-register-16bit-addr.rs:49:1
   |
49 | / device_driver::create_device!(
50 | |     device_name: MyTestDevice,
51 | |     dsl: {
52 | |         config {
...  |
81 | | );
   | | ^
   | | |
   | |_expected `u16`, found `u8`
   |   arguments to this function are incorrect
```

https://github.com/IsaacDynamo/device-driver/blob/94401ea4e77fff3a9fe545b08990b4defb878a5a/device-driver/tests/basic-register-16bit-addr.rs

Using 16bit address works on v1.0.4.

**Comment by diondokter** [comment]
Thanks for trying out master! I made a huge refactor and sadly I'm missing some things. I really need more complete automated testing: #90
